version: 2
machine:
  services:
    - docker

jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:a54b1def60625bd47c4dc7b1cd9f1575a9eb146988ec1da8ca637fb4a47b7eb9
    environment:
      - NPM_CONFIG_LOGLEVEL: warn
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Installing Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - deploy:
          name: Semantic Release
          command: npm run semantic-release
